#!/bin/bash

if [[ "$#" != "0" ]]; then
  echo "Invalid arguments!"
  exit 1
fi

if [[ -z "${VIDEO_WIDTH}" ]]; then
  echo "Run this script only with the environment from navtalink-video.env!"
  exit 1
fi

set -e

/usr/bin/gst-launch-1.0 -v v4l2src device=/dev/video1 ! videoconvert ! \
"video/x-raw,width=$VIDEO_WIDTH,height=$VIDEO_HEIGHT,framerate=$VIDEO_FRAMERATE" ! omxh264enc target-bitrate="$TARGET_BITRATE" control-rate=$H264_CONTROL_RATE ! \
 "video/x-h264,profile=$H264_PROFILE" ! h264parse ! rtph264pay ! udpsink host=127.0.0.1 port=5602
